name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install project dependencies
      run: (cd functions && yarn)
    - name: Build project
      run: (cd functions && yarn run build)
    - name: Run DEV Server
      uses: w9jds/firebase-action@master
      with:
        args: |
          emulators:start --inspect-functions 9000
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    - name: Request index.html
      run: curl localhost:5000
